services:
  backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./projects:/app/projects
      - ./temps:/app/temps
    environment:
      - NODE_ENV=development
    restart: always
